# Generated by Django 6.0 on 2025-12-29 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diseaseinfo',
            options={},
        ),
        migrations.RenameField(
            model_name='diseaseprediction',
            old_name='timestamp',
            new_name='date',
        ),
        migrations.AddField(
            model_name='diseaseprediction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diseaseprediction',
            name='image',
            field=models.ImageField(upload_to='prediction_logs/'),
        ),
    ]
